// Auto-generated
let project = new Project('eight_directions_1_0_3');

project.addSources('Sources');
project.addLibrary("/home/timidtlk/Downloads/armsdk/armory");
project.addLibrary("/home/timidtlk/Downloads/armsdk/iron");
project.addLibrary("/home/timidtlk/Downloads/armsdk/lib/haxebullet");
project.addParameter('armory.trait.physics.bullet.PhysicsWorld');
project.addParameter("--macro keep('armory.trait.physics.bullet.PhysicsWorld')");
project.addParameter('armory.trait.internal.DebugConsole');
project.addParameter("--macro keep('armory.trait.internal.DebugConsole')");
project.addParameter('arm.node.LN_character_movement');
project.addParameter("--macro keep('arm.node.LN_character_movement')");
project.addParameter('armory.trait.internal.UniformsManager');
project.addParameter("--macro keep('armory.trait.internal.UniformsManager')");
project.addParameter('armory.trait.internal.Bridge');
project.addParameter("--macro keep('armory.trait.internal.Bridge')");
project.addParameter('armory.trait.internal.CanvasScript');
project.addParameter("--macro keep('armory.trait.internal.CanvasScript')");
project.addParameter('arm.node.LN_camera_controller');
project.addParameter("--macro keep('arm.node.LN_camera_controller')");
project.addParameter('armory.trait.physics.bullet.RigidBody');
project.addParameter("--macro keep('armory.trait.physics.bullet.RigidBody')");
project.addShaders("build_eight_directions/compiled/Shaders/*.glsl", { noembed: false});
project.addAssets("build_eight_directions/compiled/Assets/**", { notinlist: true });
project.addAssets("build_eight_directions/compiled/Shaders/*.arm", { notinlist: true });
project.addAssets("/home/timidtlk/Downloads/armsdk/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("/home/timidtlk/Downloads/armsdk/armory/Assets/clouds_base.raw", { notinlist: true });
project.addAssets("/home/timidtlk/Downloads/armsdk/armory/Assets/clouds_detail.raw", { notinlist: true });
project.addAssets("/home/timidtlk/Downloads/armsdk/armory/Assets/clouds_map.png", { notinlist: true });
project.addAssets("/home/timidtlk/Downloads/armsdk/armory/Assets/hosek/hosek_radiance.hdr", { notinlist: true });
project.addAssets("/home/timidtlk/Downloads/armsdk/armory/Assets/hosek/hosek_radiance_0.hdr", { notinlist: true });
project.addAssets("/home/timidtlk/Downloads/armsdk/armory/Assets/hosek/hosek_radiance_1.hdr", { notinlist: true });
project.addAssets("/home/timidtlk/Downloads/armsdk/armory/Assets/hosek/hosek_radiance_2.hdr", { notinlist: true });
project.addAssets("/home/timidtlk/Downloads/armsdk/armory/Assets/hosek/hosek_radiance_3.hdr", { notinlist: true });
project.addAssets("/home/timidtlk/Downloads/armsdk/armory/Assets/hosek/hosek_radiance_4.hdr", { notinlist: true });
project.addAssets("/home/timidtlk/Downloads/armsdk/armory/Assets/hosek/hosek_radiance_5.hdr", { notinlist: true });
project.addAssets("/home/timidtlk/Downloads/armsdk/armory/Assets/hosek/hosek_radiance_6.hdr", { notinlist: true });
project.addAssets("/home/timidtlk/Downloads/armsdk/armory/Assets/hosek/hosek_radiance_7.hdr", { notinlist: true });
project.addAssets("/home/timidtlk/Downloads/armsdk/armory/Assets/smaa_area.png", { notinlist: true });
project.addAssets("/home/timidtlk/Downloads/armsdk/armory/Assets/smaa_search.png", { notinlist: true });
project.addAssets("Bundled/canvas/_themes.json", { notinlist: true });
project.addAssets("Bundled/canvas/print.files", { notinlist: true });
project.addAssets("Bundled/canvas/print.json", { notinlist: true });
project.addShaders("/home/timidtlk/Downloads/armsdk/armory/Shaders/debug_draw/line.vert.glsl");
project.addLibrary("/home/timidtlk/Downloads/armsdk/lib/zui");
project.addAssets("/home/timidtlk/Downloads/armsdk/armory/Assets/font_default.ttf", { notinlist: false });
project.addDefine('arm_hosek');
project.addDefine('arm_deferred');
project.addDefine('arm_csm');
project.addDefine('arm_shadowmap_atlas');
project.addDefine('rp_shadowmap_atlas_max_size_point=8192');
project.addDefine('rp_shadowmap_atlas_max_size_spot=8192');
project.addDefine('rp_shadowmap_atlas_max_size_sun=8192');
project.addDefine('rp_shadowmap_atlas_max_size=8192');
project.addDefine('rp_max_lights_cluster=16');
project.addDefine('rp_max_lights=16');
project.addDefine('arm_clusters');
project.addDefine('rp_hdr');
project.addDefine('rp_renderer=Deferred');
project.addDefine('rp_depthprepass');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_cascade=4096');
project.addDefine('rp_shadowmap_cube=2048');
project.addDefine('rp_background=World');
project.addDefine('rp_render_to_texture');
project.addDefine('rp_compositornodes');
project.addDefine('rp_antialiasing=SMAA');
project.addDefine('arm_veloc');
project.addDefine('rp_supersampling=1');
project.addDefine('rp_ssgi=SSAO');
project.addDefine('rp_ssr');
project.addDefine('rp_ssr_half');
project.addDefine('rp_overlays');
project.addDefine('rp_translucency');
project.addDefine('rp_decals');
project.addDefine('rp_blending');
project.addDefine('rp_depth_texture');
project.addDefine('rp_sss');
project.addDefine('rp_motionblur=Object');
project.addDefine('rp_pp');
project.addDefine('rp_gbuffer2');
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
project.addDefine('arm_assert_level=Warning');
project.addDefine('arm_soundcompress');
project.addDefine('arm_audio');
project.addDefine('arm_debug');
project.addDefine('arm_ui');
project.addDefine('arm_skin');
project.addDefine('arm_morph_target');
project.addDefine('arm_particles');
project.addDefine('arm_draworder_shader');
project.addDefine('armory');
project.targetOptions.android_native.package = 'org.armory3d';
project.targetOptions.android_native.screenOrientation = 'landscape';
project.targetOptions.android_native.compileSdkVersion = '30';
project.targetOptions.android_native.minSdkVersion = '23';
project.targetOptions.android_native.targetSdkVersion = '26';


resolve(project);
