package arm.node;

@:access(armory.logicnode.LogicNode)@:keep class LN_character_movement extends armory.logicnode.LogicTree {

	var functionNodes:Map<String, armory.logicnode.FunctionNode>;

	var functionOutputNodes:Map<String, armory.logicnode.FunctionOutputNode>;

	public function new() {
		super();
		name = "LN_character_movement";
		this.functionNodes = new Map();
		this.functionOutputNodes = new Map();
		notifyOnAdd(add);
	}

	override public function add() {
		var _SetObjectProperty_002 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_002.preallocInputs(4);
		_SetObjectProperty_002.preallocOutputs(1);
		var _Keyboard_002 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_002.property0 = "down";
		_Keyboard_002.property1 = "a";
		_Keyboard_002.preallocInputs(0);
		_Keyboard_002.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Keyboard_002, _SetObjectProperty_002, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, "player_hitbox"), _SetObjectProperty_002, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "key"), _SetObjectProperty_002, 0, 2);
		var _String_002 = new armory.logicnode.StringNode(this);
		_String_002.preallocInputs(1);
		_String_002.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "a"), _String_002, 0, 0);
		armory.logicnode.LogicNode.addLink(_String_002, _SetObjectProperty_002, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_002, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_003 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_003.preallocInputs(4);
		_SetObjectProperty_003.preallocOutputs(1);
		var _Keyboard_003 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_003.property0 = "down";
		_Keyboard_003.property1 = "d";
		_Keyboard_003.preallocInputs(0);
		_Keyboard_003.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Keyboard_003, _SetObjectProperty_003, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, "player_hitbox"), _SetObjectProperty_003, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "key"), _SetObjectProperty_003, 0, 2);
		var _String_003 = new armory.logicnode.StringNode(this);
		_String_003.preallocInputs(1);
		_String_003.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "d"), _String_003, 0, 0);
		armory.logicnode.LogicNode.addLink(_String_003, _SetObjectProperty_003, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_003, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty.preallocInputs(4);
		_SetObjectProperty.preallocOutputs(1);
		var _Keyboard = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard.property0 = "down";
		_Keyboard.property1 = "w";
		_Keyboard.preallocInputs(0);
		_Keyboard.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Keyboard, _SetObjectProperty, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, "player_hitbox"), _SetObjectProperty, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "key"), _SetObjectProperty, 0, 2);
		var _String = new armory.logicnode.StringNode(this);
		_String.preallocInputs(1);
		_String.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "w"), _String, 0, 0);
		armory.logicnode.LogicNode.addLink(_String, _SetObjectProperty, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_001 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_001.preallocInputs(4);
		_SetObjectProperty_001.preallocOutputs(1);
		var _Keyboard_001 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_001.property0 = "down";
		_Keyboard_001.property1 = "s";
		_Keyboard_001.preallocInputs(0);
		_Keyboard_001.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Keyboard_001, _SetObjectProperty_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, "player_hitbox"), _SetObjectProperty_001, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "key"), _SetObjectProperty_001, 0, 2);
		var _String_001 = new armory.logicnode.StringNode(this);
		_String_001.preallocInputs(1);
		_String_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "s"), _String_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_String_001, _SetObjectProperty_001, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_001, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectRotation = new armory.logicnode.SetRotationNode(this);
		_SetObjectRotation.property0 = "Euler Angles";
		_SetObjectRotation.preallocInputs(3);
		_SetObjectRotation.preallocOutputs(1);
		var _Gate = new armory.logicnode.GateNode(this);
		_Gate.property0 = "Or";
		_Gate.property1 = 9.999999747378752e-05;
		_Gate.preallocInputs(5);
		_Gate.preallocOutputs(2);
		var _OnUpdate = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate.property0 = "Update";
		_OnUpdate.preallocInputs(0);
		_OnUpdate.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_OnUpdate, _Gate, 0, 0);
		armory.logicnode.LogicNode.addLink(_Keyboard, _Gate, 1, 1);
		armory.logicnode.LogicNode.addLink(_Keyboard_001, _Gate, 1, 2);
		armory.logicnode.LogicNode.addLink(_Keyboard_002, _Gate, 1, 3);
		armory.logicnode.LogicNode.addLink(_Keyboard_003, _Gate, 1, 4);
		armory.logicnode.LogicNode.addLink(_Gate, _SetObjectRotation, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, "player_hitbox"), _SetObjectRotation, 0, 1);
		var _LookAt = new armory.logicnode.LookAtNode(this);
		_LookAt.property0 = "Y";
		_LookAt.preallocInputs(2);
		_LookAt.preallocOutputs(1);
		var _GetObjectLocation = new armory.logicnode.GetLocationNode(this);
		_GetObjectLocation.preallocInputs(2);
		_GetObjectLocation.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, "player_hitbox"), _GetObjectLocation, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _GetObjectLocation, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectLocation, _LookAt, 0, 0);
		var _GetObjectLocation_001 = new armory.logicnode.GetLocationNode(this);
		_GetObjectLocation_001.preallocInputs(2);
		_GetObjectLocation_001.preallocOutputs(1);
		var _GetObjectbyName = new armory.logicnode.GetObjectNode(this);
		_GetObjectbyName.preallocInputs(1);
		_GetObjectbyName.preallocOutputs(1);
		var _GetObjectProperty = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty.preallocInputs(2);
		_GetObjectProperty.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, "player_hitbox"), _GetObjectProperty, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "key"), _GetObjectProperty, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty, _GetObjectbyName, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectbyName, _GetObjectLocation_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _GetObjectLocation_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectLocation_001, _LookAt, 0, 1);
		armory.logicnode.LogicNode.addLink(_LookAt, _SetObjectRotation, 0, 2);
		armory.logicnode.LogicNode.addLink(_SetObjectRotation, new armory.logicnode.NullNode(this), 0, 0);
		var _TranslateObject = new armory.logicnode.TranslateObjectNode(this);
		_TranslateObject.preallocInputs(4);
		_TranslateObject.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_Gate, _TranslateObject, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, "player_hitbox"), _TranslateObject, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.VectorNode(this, 0.0,0.10000000149011612,0.0), _TranslateObject, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _TranslateObject, 0, 3);
		armory.logicnode.LogicNode.addLink(_TranslateObject, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_008 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_008.preallocInputs(4);
		_SetObjectProperty_008.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_Gate, _SetObjectProperty_008, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, "player_hitbox"), _SetObjectProperty_008, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "action"), _SetObjectProperty_008, 0, 2);
		var _String_008 = new armory.logicnode.StringNode(this);
		_String_008.preallocInputs(1);
		_String_008.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "run"), _String_008, 0, 0);
		armory.logicnode.LogicNode.addLink(_String_008, _SetObjectProperty_008, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_008, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_005 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_005.preallocInputs(4);
		_SetObjectProperty_005.preallocOutputs(1);
		var _Gate_002 = new armory.logicnode.GateNode(this);
		_Gate_002.property0 = "And";
		_Gate_002.property1 = 9.999999747378752e-05;
		_Gate_002.preallocInputs(3);
		_Gate_002.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_OnUpdate, _Gate_002, 0, 0);
		armory.logicnode.LogicNode.addLink(_Keyboard_001, _Gate_002, 0, 1);
		armory.logicnode.LogicNode.addLink(_Keyboard_002, _Gate_002, 0, 2);
		armory.logicnode.LogicNode.addLink(_Gate_002, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_Gate_002, _SetObjectProperty_005, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, "player_hitbox"), _SetObjectProperty_005, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "key"), _SetObjectProperty_005, 0, 2);
		var _String_005 = new armory.logicnode.StringNode(this);
		_String_005.preallocInputs(1);
		_String_005.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "as"), _String_005, 0, 0);
		armory.logicnode.LogicNode.addLink(_String_005, _SetObjectProperty_005, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_005, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_006 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_006.preallocInputs(4);
		_SetObjectProperty_006.preallocOutputs(1);
		var _Gate_003 = new armory.logicnode.GateNode(this);
		_Gate_003.property0 = "And";
		_Gate_003.property1 = 9.999999747378752e-05;
		_Gate_003.preallocInputs(3);
		_Gate_003.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_OnUpdate, _Gate_003, 0, 0);
		armory.logicnode.LogicNode.addLink(_Keyboard_001, _Gate_003, 0, 1);
		armory.logicnode.LogicNode.addLink(_Keyboard_003, _Gate_003, 0, 2);
		armory.logicnode.LogicNode.addLink(_Gate_003, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_Gate_003, _SetObjectProperty_006, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, "player_hitbox"), _SetObjectProperty_006, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "key"), _SetObjectProperty_006, 0, 2);
		var _String_006 = new armory.logicnode.StringNode(this);
		_String_006.preallocInputs(1);
		_String_006.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "sd"), _String_006, 0, 0);
		armory.logicnode.LogicNode.addLink(_String_006, _SetObjectProperty_006, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_006, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_007 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_007.preallocInputs(4);
		_SetObjectProperty_007.preallocOutputs(1);
		var _Gate_004 = new armory.logicnode.GateNode(this);
		_Gate_004.property0 = "And";
		_Gate_004.property1 = 9.999999747378752e-05;
		_Gate_004.preallocInputs(3);
		_Gate_004.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_OnUpdate, _Gate_004, 0, 0);
		armory.logicnode.LogicNode.addLink(_Keyboard_003, _Gate_004, 0, 1);
		armory.logicnode.LogicNode.addLink(_Keyboard, _Gate_004, 0, 2);
		armory.logicnode.LogicNode.addLink(_Gate_004, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_Gate_004, _SetObjectProperty_007, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, "player_hitbox"), _SetObjectProperty_007, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "key"), _SetObjectProperty_007, 0, 2);
		var _String_007 = new armory.logicnode.StringNode(this);
		_String_007.preallocInputs(1);
		_String_007.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "dw"), _String_007, 0, 0);
		armory.logicnode.LogicNode.addLink(_String_007, _SetObjectProperty_007, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_007, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_009 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_009.preallocInputs(4);
		_SetObjectProperty_009.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_Gate, _SetObjectProperty_009, 1, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, "player_hitbox"), _SetObjectProperty_009, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "action"), _SetObjectProperty_009, 0, 2);
		var _String_009 = new armory.logicnode.StringNode(this);
		_String_009.preallocInputs(1);
		_String_009.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "idle"), _String_009, 0, 0);
		armory.logicnode.LogicNode.addLink(_String_009, _SetObjectProperty_009, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_009, new armory.logicnode.NullNode(this), 0, 0);
		var _SetCanvasText = new armory.logicnode.CanvasSetTextNode(this);
		_SetCanvasText.preallocInputs(3);
		_SetCanvasText.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_OnUpdate, _SetCanvasText, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "Text"), _SetCanvasText, 0, 1);
		var _GetObjectProperty_001 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_001.preallocInputs(2);
		_GetObjectProperty_001.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, "player_hitbox"), _GetObjectProperty_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "action"), _GetObjectProperty_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_001, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_001, _SetCanvasText, 0, 2);
		armory.logicnode.LogicNode.addLink(_SetCanvasText, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_004 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_004.preallocInputs(4);
		_SetObjectProperty_004.preallocOutputs(1);
		var _Gate_001 = new armory.logicnode.GateNode(this);
		_Gate_001.property0 = "And";
		_Gate_001.property1 = 9.999999747378752e-05;
		_Gate_001.preallocInputs(3);
		_Gate_001.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_OnUpdate, _Gate_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_Keyboard, _Gate_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_Keyboard_002, _Gate_001, 0, 2);
		armory.logicnode.LogicNode.addLink(_Gate_001, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_Gate_001, _SetObjectProperty_004, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, "player_hitbox"), _SetObjectProperty_004, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "key"), _SetObjectProperty_004, 0, 2);
		var _String_004 = new armory.logicnode.StringNode(this);
		_String_004.preallocInputs(1);
		_String_004.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "wa"), _String_004, 0, 0);
		armory.logicnode.LogicNode.addLink(_String_004, _SetObjectProperty_004, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_004, new armory.logicnode.NullNode(this), 0, 0);
		var _PlayActionFrom_001 = new armory.logicnode.PlayActionFromNode(this);
		_PlayActionFrom_001.preallocInputs(9);
		_PlayActionFrom_001.preallocOutputs(2);
		var _Gate_005 = new armory.logicnode.GateNode(this);
		_Gate_005.property0 = "Equal";
		_Gate_005.property1 = 9.999999747378752e-05;
		_Gate_005.preallocInputs(3);
		_Gate_005.preallocOutputs(2);
		var _ValueChanged = new armory.logicnode.ValueChangedNode(this);
		_ValueChanged.preallocInputs(2);
		_ValueChanged.preallocOutputs(3);
		var _OnUpdate_001 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_001.property0 = "Update";
		_OnUpdate_001.preallocInputs(0);
		_OnUpdate_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_OnUpdate_001, _ValueChanged, 0, 0);
		var _GetObjectProperty_002 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_002.preallocInputs(2);
		_GetObjectProperty_002.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, "player_hitbox"), _GetObjectProperty_002, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "action"), _GetObjectProperty_002, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_002, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_002, _ValueChanged, 0, 1);
		armory.logicnode.LogicNode.addLink(_ValueChanged, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_ValueChanged, new armory.logicnode.NullNode(this), 2, 0);
		armory.logicnode.LogicNode.addLink(_ValueChanged, _Gate_005, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_002, _Gate_005, 0, 1);
		var _String_010 = new armory.logicnode.StringNode(this);
		_String_010.preallocInputs(1);
		_String_010.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "idle"), _String_010, 0, 0);
		armory.logicnode.LogicNode.addLink(_String_010, _Gate_005, 0, 2);
		armory.logicnode.LogicNode.addLink(_Gate_005, _PlayActionFrom_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, "armature"), _PlayActionFrom_001, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "Idle"), _PlayActionFrom_001, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 0), _PlayActionFrom_001, 0, 3);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 59), _PlayActionFrom_001, 0, 4);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.25), _PlayActionFrom_001, 0, 5);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 1.0), _PlayActionFrom_001, 0, 6);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _PlayActionFrom_001, 0, 7);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _PlayActionFrom_001, 0, 8);
		armory.logicnode.LogicNode.addLink(_PlayActionFrom_001, new armory.logicnode.NullNode(this), 0, 0);
		armory.logicnode.LogicNode.addLink(_PlayActionFrom_001, new armory.logicnode.NullNode(this), 1, 0);
		var _PlayActionFrom = new armory.logicnode.PlayActionFromNode(this);
		_PlayActionFrom.preallocInputs(9);
		_PlayActionFrom.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Gate_005, _PlayActionFrom, 1, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, "armature"), _PlayActionFrom, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "running"), _PlayActionFrom, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 0), _PlayActionFrom, 0, 3);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 22), _PlayActionFrom, 0, 4);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.25), _PlayActionFrom, 0, 5);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 1.0), _PlayActionFrom, 0, 6);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _PlayActionFrom, 0, 7);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _PlayActionFrom, 0, 8);
		armory.logicnode.LogicNode.addLink(_PlayActionFrom, new armory.logicnode.NullNode(this), 0, 0);
		armory.logicnode.LogicNode.addLink(_PlayActionFrom, new armory.logicnode.NullNode(this), 1, 0);
	}
}